name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<GOOGLE_OAUTH_CLIENT_ID>"
          replace: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<GOOGLE_OAUTH_CLIENT_SECRET>"
          replace: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          regex: false

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_RAW }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/tactile-alloy-392517/bigquery-example:latest
          build-args: |
            HTTP_PORT=8080

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/tactile-alloy-392517/bigquery-example:latest
          service: bigquery-example
          region: us-east1